
version: 2

models:
  - name: customers
    description: "customers in coffee shop"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: monthly_new_customers
    description: "A starter dbt model"
    columns:
      - name: signup_month
        description: "The primary key for this table"
